#include <thread>
#include "log/log.h"
#include <iostream>


void thread_1()
{
	while(true)
	{
		LOG(DEBUG_LEVEL, "%s","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
		LOG(INFO_LEVEL, "%s","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
		LOG(WARN_LEVEL, "%s","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
		LOG(ERROR_LEVEL, "%s","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
		LOG(CRITIC_LEVEL, "%s","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
	}
}


void thread_2()
{
	while(true)
	{
		LOG(DEBUG_LEVEL, "%s","BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		LOG(INFO_LEVEL, "%s","BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		LOG(WARN_LEVEL, "%s","BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		LOG(ERROR_LEVEL, "%s","BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		LOG(CRITIC_LEVEL, "%s","BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
	}

}

void thread_3()
{
	while(true)
	{
		LOG(DEBUG_LEVEL, "%s","CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC");
		LOG(INFO_LEVEL, "%s","CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC");
		LOG(WARN_LEVEL, "%s","CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC");
		LOG(ERROR_LEVEL, "%s","CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC");
		LOG(CRITIC_LEVEL, "%s","CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC");
	}

}

void thread_4()
{
	while(true)
	{
		LOG(DEBUG_LEVEL, "%s","DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD");
		LOG(INFO_LEVEL, "%s","DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD");
		LOG(WARN_LEVEL, "%s","DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD");
		LOG(ERROR_LEVEL, "%s","DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD");
		LOG(CRITIC_LEVEL, "%s","DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD");
	}

}

void thread_5()
{
	while(true)
	{
		LOG(DEBUG_LEVEL, "%s","EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE");
		LOG(INFO_LEVEL, "%s","EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE");
		LOG(WARN_LEVEL, "%s","EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE");
		LOG(ERROR_LEVEL, "%s","EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE");
		LOG(CRITIC_LEVEL, "%s","EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE");
	}

}



int main()
{

	initlog(".\\logs", 10, 1, 2, true, true, true);

	std::thread th1(thread_1);
	std::thread th2(thread_2);
	std::thread th3(thread_3);
	std::thread th4(thread_4);
	std::thread th5(thread_5);
	
	getchar();
	stoplog();
	return 0;
}
